"""Country name mapping: canonical English key -> list of variants in other languages.

Variants are matched case-insensitively against the `country_account` column.
All variants must be stored lowercased.
"""

COUNTRIES: dict[str, list[str]] = {
    "USA": [
        "united states",
        "united states of america",
        "usa",
        "u.s.a.",
        "u.s.",
        "сполучені штати америки",
        "сша",
        "соединенные штаты америки",
        "соединённые штаты америки",
        "amerikas savienotās valstis",
        "verenigde staten",
        "vs",
        "états-unis",
        "etats-unis",
        "vereinigte staaten",
        "vereinigte staaten von amerika",
        "stati uniti",
        "stati uniti d'america",
        "estados unidos",
        "estados unidos de américa",
        "estados unidos da américa",
        "アメリカ合衆国",
        "米国",
        "stany zjednoczone",
        "amerika birleşik devletleri",
        "美国",
        "美利坚合众国",
        "미국",
    ],
    "UK": [
        "united kingdom",
        "uk",
        "great britain",
        "britain",
        "england",
        "велика британія",
        "великобритания",
        "англия",
        "британия",
        "apvienotā karaliste",
        "verenigd koninkrijk",
        "royaume-uni",
        "großbritannien",
        "vereinigtes königreich",
        "regno unito",
        "reino unido",
        "イギリス",
        "英国",
        "wielka brytania",
        "birleşik krallık",
        "英国",
        "영국",
    ],
    "Germany": [
        "germany",
        "німеччина",
        "германия",
        "vācija",
        "duitsland",
        "allemagne",
        "deutschland",
        "germania",
        "alemanha",
        "alemania",
        "ドイツ",
        "niemcy",
        "almanya",
        "德国",
        "독일",
    ],
    "France": [
        "france",
        "francia",
        "франція",
        "франция",
        "frankrijk",
        "frankreich",
        "francja",
        "fransa",
        "フランス",
        "法国",
        "프랑스",
    ],
    "Italy": [
        "italy",
        "італія",
        "италия",
        "itālija",
        "italië",
        "italie",
        "italien",
        "italia",
        "włochy",
        "イタリア",
        "意大利",
        "이탈리아",
    ],
    "Canada": [
        "canada",
        "канада",
        "kanāda",
        "kanada",
        "カナダ",
        "加拿大",
        "캐나다",
    ],
    "Spain": [
        "spain",
        "іспанія",
        "испания",
        "spānija",
        "spanje",
        "espagne",
        "spanien",
        "spagna",
        "españa",
        "espanha",
        "hiszpania",
        "ispanya",
        "スペイン",
        "西班牙",
        "스페인",
    ],
    "Australia": [
        "australia",
        "австралія",
        "австралия",
        "austrālija",
        "australië",
        "australie",
        "australien",
        "austrália",
        "オーストラリア",
        "avustralya",
        "澳大利亚",
        "호주",
    ],
    "Japan": [
        "japan",
        "японія",
        "япония",
        "japāna",
        "japon",
        "giappone",
        "japón",
        "japão",
        "日本",
        "japonya",
        "japonia",
        "일본",
    ],
    "Netherlands": [
        "netherlands",
        "the netherlands",
        "holland",
        "нідерланди",
        "нидерланды",
        "голландия",
        "nīderlande",
        "nederland",
        "pays-bas",
        "niederlande",
        "paesi bassi",
        "países bajos",
        "países baixos",
        "オランダ",
        "holandia",
        "hollanda",
        "荷兰",
        "네덜란드",
    ],
    "Austria": [
        "austria",
        "австрія",
        "австрия",
        "austrija",
        "oostenrijk",
        "autriche",
        "österreich",
        "áustria",
        "オーストリア",
        "avusturya",
        "奥地利",
        "오스트리아",
    ],
    "Denmark": [
        "denmark",
        "данія",
        "дания",
        "dānija",
        "denemarken",
        "danemark",
        "dänemark",
        "danimarca",
        "dinamarca",
        "デンマーク",
        "dania",
        "danimarka",
        "丹麦",
        "덴마크",
    ],
    "Belgium": [
        "belgium",
        "бельгія",
        "бельгия",
        "beļģija",
        "belgië",
        "belgique",
        "belgien",
        "belgio",
        "bélgica",
        "ベルギー",
        "belgia",
        "belçika",
        "比利时",
        "벨기에",
    ],
    "Switzerland": [
        "switzerland",
        "швейцарія",
        "швейцария",
        "šveice",
        "zwitserland",
        "suisse",
        "schweiz",
        "svizzera",
        "suiza",
        "suíça",
        "スイス",
        "szwajcaria",
        "isviçre",
        "瑞士",
        "스위스",
    ],
    "India": [
        "india",
        "індія",
        "индия",
        "indija",
        "indien",
        "inde",
        "índia",
        "インド",
        "indie",
        "hindistan",
        "印度",
        "인도",
    ],
    "Mexico": [
        "mexico",
        "мексика",
        "meksika",
        "mexique",
        "messico",
        "méxico",
        "メキシコ",
        "meksyk",
        "墨西哥",
        "멕시코",
    ],
    "Sweden": [
        "sweden",
        "швеція",
        "швеция",
        "zviedrija",
        "zweden",
        "suède",
        "schweden",
        "svezia",
        "suecia",
        "suécia",
        "スウェーデン",
        "szwecja",
        "isveç",
        "瑞典",
        "스웨덴",
    ],
    "Brazil": [
        "brazil",
        "бразилія",
        "бразилия",
        "brazīlija",
        "brazilië",
        "brésil",
        "brasilien",
        "brasile",
        "brasil",
        "ブラジル",
        "brazylia",
        "brezilya",
        "巴西",
        "브라질",
    ],
    "Ireland": [
        "ireland",
        "ierland",
        "ірландія",
        "ирландия",
        "īrija",
        "irlande",
        "irland",
        "irlanda",
        "アイルランド",
        "irlandia",
        "irlanda",
        "爱尔兰",
        "아일랜드",
    ],
    "Portugal": [
        "portugal",
        "португалія",
        "португалия",
        "portugāle",
        "portogallo",
        "ポルトガル",
        "portekiz",
        "葡萄牙",
        "포르투갈",
    ],
    "New Zealand": [
        "new zealand",
        "нова зеландія",
        "новая зеландия",
        "jaunzēlande",
        "nieuw-zeeland",
        "nouvelle-zélande",
        "neuseeland",
        "nuova zelanda",
        "nueva zelanda",
        "nova zelândia",
        "ニュージーランド",
        "nowa zelandia",
        "yeni zelanda",
        "新西兰",
        "뉴질랜드",
    ],
    "Norway": [
        "norway",
        "норвегія",
        "норвегия",
        "norvēģija",
        "noorwegen",
        "norvège",
        "norwegen",
        "norvegia",
        "noruega",
        "ノルウェー",
        "norwegia",
        "norveç",
        "挪威",
        "노르웨이",
    ],
    "Israel": [
        "israel",
        "ізраїль",
        "израиль",
        "izraēla",
        "israël",
        "israele",
        "イスラエル",
        "izrael",
        "以色列",
        "이스라엘",
    ],
    "Philippines": [
        "philippines",
        "філіппіни",
        "филиппины",
        "filipīnas",
        "filipijnen",
        "filippinen",
        "filippine",
        "filipinas",
        "フィリピン",
        "filipiny",
        "filipinler",
        "菲律宾",
        "필리핀",
    ],
    "South Korea": [
        "south korea",
        "korea",
        "republic of korea",
        "південна корея",
        "южная корея",
        "корея",
        "dienvidkoreja",
        "zuid-korea",
        "corée du sud",
        "südkorea",
        "corea del sud",
        "corea del sur",
        "coreia do sul",
        "韓国",
        "大韓民国",
        "korea południowa",
        "güney kore",
        "韩国",
        "大韩民国",
        "대한민국",
        "한국",
    ],
    "Nigeria": [
        "nigeria",
        "нігерія",
        "нигерия",
        "nigērija",
        "nigéria",
        "ナイジェリア",
        "nijerya",
        "尼日利亚",
        "나이지리아",
    ],
    "Poland": [
        "poland",
        "польща",
        "польша",
        "polija",
        "polen",
        "pologne",
        "polonia",
        "polônia",
        "polonia",
        "ポーランド",
        "polska",
        "polonya",
        "波兰",
        "폴란드",
    ],
    "Indonesia": [
        "indonesia",
        "індонезія",
        "индонезия",
        "indonēzija",
        "indonesië",
        "indonésie",
        "indonésia",
        "インドネシア",
        "endonezya",
        "印度尼西亚",
        "인도네시아",
    ],
    "Russia": [
        "russia",
        "russian federation",
        "росія",
        "россия",
        "российская федерация",
        "krievija",
        "rusland",
        "russie",
        "russland",
        "rusia",
        "rússia",
        "ロシア",
        "rosja",
        "rusya",
        "俄罗斯",
        "러시아",
    ],
    "Argentina": [
        "argentina",
        "аргентина",
        "argentīna",
        "argentinië",
        "argentine",
        "argentinien",
        "アルゼンチン",
        "argentyna",
        "arjantin",
        "阿根廷",
        "아르헨티나",
    ],
}

EMPTY_COUNTRY_VALUES = {"", "не поширюється", "не применяется", "n/a", "—"}


def build_allowed_set(checked_keys: list[str], custom_text: str) -> set[str]:
    """Build a lowercased set of acceptable country_account values.

    `checked_keys` — list of canonical English keys from COUNTRIES.
    `custom_text` — free-form latin input, comma- or newline-separated.
    """
    allowed: set[str] = set()
    for key in checked_keys:
        for variant in COUNTRIES.get(key, []):
            allowed.add(variant.lower().strip())

    if custom_text:
        for token in custom_text.replace("\n", ",").split(","):
            token = token.strip().lower()
            if token:
                allowed.add(token)

    return allowed
