"""Country name mapping: canonical English key -> list of variants in other languages.

Variants are matched case-insensitively against the `country_account` column.
All variants must be stored lowercased.

`TIERS` groups country keys into marketing tiers used by the GUI.
"""

COUNTRIES: dict[str, list[str]] = {
    # ---------------- Tier 1 ----------------
    "USA": [
        "united states",
        "united states of america",
        "usa",
        "u.s.a.",
        "u.s.",
        "сполучені штати америки",
        "сша",
        "соединенные штаты америки",
        "соединённые штаты америки",
        "amerikas savienotās valstis",
        "verenigde staten",
        "vs",
        "états-unis",
        "etats-unis",
        "vereinigte staaten",
        "vereinigte staaten von amerika",
        "stati uniti",
        "stati uniti d'america",
        "estados unidos",
        "estados unidos de américa",
        "estados unidos da américa",
        "アメリカ合衆国",
        "米国",
        "stany zjednoczone",
        "amerika birleşik devletleri",
        "美国",
        "美利坚合众国",
        "美國",
        "미국",
        "yhdysvallat",
        "združene države",
        "združene države amerike",
        "spojené státy americké",
        "spojené státy",
        "amerika serikat",
        "spojené štáty americké",
    ],
    "UK": [
        "united kingdom",
        "uk",
        "great britain",
        "britain",
        "england",
        "велика британія",
        "великобритания",
        "англия",
        "британия",
        "apvienotā karaliste",
        "verenigd koninkrijk",
        "royaume-uni",
        "großbritannien",
        "vereinigtes königreich",
        "regno unito",
        "reino unido",
        "イギリス",
        "英国",
        "wielka brytania",
        "birleşik krallık",
        "英国",
        "영국",
        "yhdistynyt kuningaskunta",
        "združeno kraljestvo",
        "spojené království",
        "spojené kráľovstvo",
        "inggris raya",
    ],
    "Canada": [
        "canada",
        "канада",
        "kanāda",
        "kanada",
        "カナダ",
        "加拿大",
        "캐나다",
    ],
    "Australia": [
        "australia",
        "австралія",
        "австралия",
        "austrālija",
        "australië",
        "australie",
        "australien",
        "austrália",
        "オーストラリア",
        "avustralya",
        "澳大利亚",
        "호주",
        "australija",
    ],
    "New Zealand": [
        "new zealand",
        "нова зеландія",
        "новая зеландия",
        "jaunzēlande",
        "nieuw-zeeland",
        "nouvelle-zélande",
        "neuseeland",
        "nuova zelanda",
        "nueva zelanda",
        "nova zelândia",
        "ニュージーランド",
        "nowa zelandia",
        "yeni zelanda",
        "新西兰",
        "뉴질랜드",
        "nova zelandija",
        "nový zéland",
        "selandia baru",
    ],
    "Germany": [
        "germany",
        "німеччина",
        "германия",
        "vācija",
        "duitsland",
        "allemagne",
        "deutschland",
        "germania",
        "alemanha",
        "alemania",
        "ドイツ",
        "niemcy",
        "almanya",
        "德国",
        "독일",
        "saksa",
        "nemčija",
        "německo",
        "jerman",
    ],
    "France": [
        "france",
        "francia",
        "франція",
        "франция",
        "frankrijk",
        "frankreich",
        "francja",
        "fransa",
        "フランス",
        "法国",
        "프랑스",
        "ranska",
        "francija",
        "francie",
        "francúzsko",
        "perancis",
    ],
    "Netherlands": [
        "netherlands",
        "the netherlands",
        "holland",
        "нідерланди",
        "нидерланды",
        "голландия",
        "nīderlande",
        "nederland",
        "pays-bas",
        "niederlande",
        "paesi bassi",
        "países bajos",
        "países baixos",
        "オランダ",
        "holandia",
        "hollanda",
        "荷兰",
        "네덜란드",
        "alankomaat",
        "nizozemska",
        "nizozemsko",
        "holandsko",
        "belanda",
    ],
    "Switzerland": [
        "switzerland",
        "швейцарія",
        "швейцария",
        "šveice",
        "zwitserland",
        "suisse",
        "schweiz",
        "svizzera",
        "suiza",
        "suíça",
        "スイス",
        "szwajcaria",
        "isviçre",
        "瑞士",
        "스위스",
        "sveitsi",
        "švica",
        "švýcarsko",
        "švajčiarsko",
        "swiss",
    ],
    "Austria": [
        "austria",
        "австрія",
        "австрия",
        "austrija",
        "oostenrijk",
        "autriche",
        "österreich",
        "áustria",
        "オーストリア",
        "avusturya",
        "奥地利",
        "오스트리아",
        "itävalta",
        "avstrija",
        "rakousko",
        "rakúsko",
    ],
    "Belgium": [
        "belgium",
        "бельгія",
        "бельгия",
        "beļģija",
        "belgië",
        "belgique",
        "belgien",
        "belgio",
        "bélgica",
        "ベルギー",
        "belgia",
        "belçika",
        "比利时",
        "벨기에",
        "belgija",
    ],
    "Sweden": [
        "sweden",
        "швеція",
        "швеция",
        "zviedrija",
        "zweden",
        "suède",
        "schweden",
        "svezia",
        "suecia",
        "suécia",
        "スウェーデン",
        "szwecja",
        "isveç",
        "瑞典",
        "스웨덴",
        "ruotsi",
        "švedska",
        "švédsko",
        "swedia",
    ],
    "Norway": [
        "norway",
        "норвегія",
        "норвегия",
        "norvēģija",
        "noorwegen",
        "norvège",
        "norwegen",
        "norvegia",
        "noruega",
        "ノルウェー",
        "norwegia",
        "norveç",
        "挪威",
        "노르웨이",
        "norja",
        "norveška",
        "norsko",
        "nórsko",
        "norwegia",
    ],
    "Denmark": [
        "denmark",
        "данія",
        "дания",
        "dānija",
        "denemarken",
        "danemark",
        "dänemark",
        "danimarca",
        "dinamarca",
        "デンマーク",
        "dania",
        "danimarka",
        "丹麦",
        "덴마크",
        "tanska",
        "danska",
        "dánsko",
        "denmark",
    ],
    "Finland": [
        "finland",
        "фінляндія",
        "финляндия",
        "somija",
        "finland",
        "finlande",
        "finnland",
        "finlandia",
        "finlândia",
        "フィンランド",
        "finlandiya",
        "芬兰",
        "핀란드",
        "suomi",
        "finska",
        "finsko",
        "fínsko",
    ],
    "Ireland": [
        "ireland",
        "ierland",
        "ірландія",
        "ирландия",
        "īrija",
        "irlande",
        "irland",
        "irlanda",
        "アイルランド",
        "irlandia",
        "irlanda",
        "爱尔兰",
        "아일랜드",
        "irlanti",
        "irska",
        "írsko",
    ],
    "Iceland": [
        "iceland",
        "ісландія",
        "исландия",
        "islande",
        "ijsland",
        "island",
        "islanda",
        "islandia",
        "islândia",
        "アイスランド",
        "izlanda",
        "冰岛",
        "아이슬란드",
        "islantia",
        "islanti",
        "islandija",
        "islandsko",
    ],
    "Luxembourg": [
        "luxembourg",
        "люксембург",
        "luksemburga",
        "luxemburg",
        "lussemburgo",
        "luxemburgo",
        "ルクセンブルク",
        "luksemburg",
        "lüksemburg",
        "卢森堡",
        "룩셈부르크",
        "luksemburgo",
    ],
    "Japan": [
        "japan",
        "японія",
        "япония",
        "japāna",
        "japon",
        "giappone",
        "japón",
        "japão",
        "日本",
        "japonya",
        "japonia",
        "일본",
        "jepang",
        "japonsko",
    ],
    "South Korea": [
        "south korea",
        "korea",
        "republic of korea",
        "південна корея",
        "южная корея",
        "корея",
        "dienvidkoreja",
        "zuid-korea",
        "corée du sud",
        "südkorea",
        "corea del sud",
        "corea del sur",
        "coreia do sul",
        "韓国",
        "大韓民国",
        "korea południowa",
        "güney kore",
        "韩国",
        "大韩民国",
        "대한민국",
        "한국",
        "etelä-korea",
        "južna koreja",
        "jižní korea",
        "južná kórea",
        "korea selatan",
    ],
    "Singapore": [
        "singapore",
        "сінгапур",
        "сингапур",
        "singapūra",
        "singapur",
        "singapour",
        "singapura",
        "シンガポール",
        "新加坡",
        "싱가포르",
        "singapor",
    ],
    "Israel": [
        "israel",
        "ізраїль",
        "израиль",
        "izraēla",
        "israël",
        "israele",
        "イスラエル",
        "izrael",
        "以色列",
        "이스라엘",
    ],
    # ---------------- Tier 2 ----------------
    "Italy": [
        "italy",
        "італія",
        "италия",
        "itālija",
        "italië",
        "italie",
        "italien",
        "italia",
        "włochy",
        "イタリア",
        "意大利",
        "이탈리아",
        "itálie",
        "taliansko",
        "italija",
    ],
    "Spain": [
        "spain",
        "іспанія",
        "испания",
        "spānija",
        "spanje",
        "espagne",
        "spanien",
        "spagna",
        "españa",
        "espanha",
        "hiszpania",
        "ispanya",
        "スペイン",
        "西班牙",
        "스페인",
        "espanja",
        "španija",
        "španělsko",
        "španielsko",
        "spanyol",
    ],
    "Portugal": [
        "portugal",
        "португалія",
        "португалия",
        "portugāle",
        "portogallo",
        "ポルトガル",
        "portekiz",
        "葡萄牙",
        "포르투갈",
        "portugali",
        "portugalska",
        "portugalsko",
    ],
    "Greece": [
        "greece",
        "греція",
        "греция",
        "grieķija",
        "griekenland",
        "grèce",
        "griechenland",
        "grecia",
        "grécia",
        "ギリシャ",
        "grecja",
        "yunanistan",
        "希腊",
        "그리스",
        "kreikka",
        "grčija",
        "řecko",
        "grécko",
    ],
    "Poland": [
        "poland",
        "польща",
        "польша",
        "polija",
        "polen",
        "pologne",
        "polonia",
        "polônia",
        "ポーランド",
        "polska",
        "polonya",
        "波兰",
        "폴란드",
        "puola",
        "poljska",
        "polsko",
        "poľsko",
    ],
    "Czech Republic": [
        "czech republic",
        "czechia",
        "чехія",
        "чехия",
        "čehija",
        "tsjechië",
        "république tchèque",
        "tschechien",
        "repubblica ceca",
        "república checa",
        "chéquia",
        "チェコ",
        "czechy",
        "çekya",
        "捷克",
        "체코",
        "tšekki",
        "češka",
        "česko",
    ],
    "Hungary": [
        "hungary",
        "угорщина",
        "венгрия",
        "ungārija",
        "hongarije",
        "hongrie",
        "ungarn",
        "ungheria",
        "hungría",
        "ハンガリー",
        "węgry",
        "macaristan",
        "匈牙利",
        "헝가리",
        "unkari",
        "madžarska",
        "maďarsko",
    ],
    "Slovakia": [
        "slovakia",
        "словаччина",
        "словакия",
        "slovākija",
        "slowakije",
        "slovaquie",
        "slowakei",
        "slovacchia",
        "eslovaquia",
        "eslováquia",
        "スロバキア",
        "słowacja",
        "slovakya",
        "斯洛伐克",
        "슬로바키아",
        "slovakia",
        "slovaška",
        "slovensko",
    ],
    "Croatia": [
        "croatia",
        "хорватія",
        "хорватия",
        "horvātija",
        "kroatië",
        "croatie",
        "kroatien",
        "croazia",
        "croacia",
        "croácia",
        "クロアチア",
        "chorwacja",
        "hırvatistan",
        "克罗地亚",
        "크로아티아",
        "kroatia",
        "hrvaška",
        "chorvatsko",
        "chorvátsko",
    ],
    "Romania": [
        "romania",
        "румунія",
        "румыния",
        "rumānija",
        "roemenië",
        "roumanie",
        "rumänien",
        "rumania",
        "romênia",
        "ルーマニア",
        "rumunia",
        "romanya",
        "罗马尼亚",
        "루마니아",
        "romania",
        "romunija",
        "rumunsko",
    ],
    "Bulgaria": [
        "bulgaria",
        "болгарія",
        "болгария",
        "bulgārija",
        "bulgarije",
        "bulgarie",
        "bulgarien",
        "ブルガリア",
        "bułgaria",
        "bulgaristan",
        "保加利亚",
        "불가리아",
        "bulgaaria",
        "bulgarija",
        "bulharsko",
    ],
    "Serbia": [
        "serbia",
        "сербія",
        "сербия",
        "serbija",
        "servië",
        "serbie",
        "serbien",
        "sérvia",
        "セルビア",
        "serbia",
        "sırbistan",
        "塞尔维亚",
        "세르비아",
        "srbija",
        "srbsko",
    ],
    "Russia": [
        "russia",
        "russian federation",
        "росія",
        "россия",
        "российская федерация",
        "krievija",
        "rusland",
        "russie",
        "russland",
        "rusia",
        "rússia",
        "ロシア",
        "rosja",
        "rusya",
        "俄罗斯",
        "러시아",
        "venäjä",
        "rusija",
        "rusko",
    ],
    "Ukraine": [
        "ukraine",
        "україна",
        "украина",
        "ukraina",
        "oekraïne",
        "ukraine",
        "ucrania",
        "ucraina",
        "ucrânia",
        "ウクライナ",
        "ukrayna",
        "乌克兰",
        "우크라이나",
        "ukrajina",
    ],
    "Turkey": [
        "turkey",
        "türkiye",
        "туреччина",
        "турция",
        "turcija",
        "turkije",
        "turquie",
        "türkei",
        "turchia",
        "turquía",
        "turquia",
        "トルコ",
        "turcja",
        "土耳其",
        "터키",
        "turki",
        "turkki",
        "turčija",
        "turecko",
    ],
    "UAE": [
        "united arab emirates",
        "uae",
        "об'єднані арабські емірати",
        "объединённые арабские эмираты",
        "apvienotie arābu emirāti",
        "verenigde arabische emiraten",
        "émirats arabes unis",
        "emirats arabes unis",
        "vereinigte arabische emirate",
        "emirati arabi uniti",
        "emiratos árabes unidos",
        "emirados árabes unidos",
        "アラブ首長国連邦",
        "zjednoczone emiraty arabskie",
        "birleşik arap emirlikleri",
        "阿拉伯联合酋长国",
        "아랍에미리트",
        "yhdistyneet arabiemiirikunnat",
        "združeni arabski emirati",
        "spojené arabské emiráty",
    ],
    "Saudi Arabia": [
        "saudi arabia",
        "саудівська аравія",
        "саудовская аравия",
        "saūda arābija",
        "saoedi-arabië",
        "arabie saoudite",
        "saudi-arabien",
        "arabia saudita",
        "arábia saudita",
        "サウジアラビア",
        "arabia saudyjska",
        "suudi arabistan",
        "沙特阿拉伯",
        "사우디아라비아",
        "saudská arábia",
        "saúdská arábie",
    ],
    "Hong Kong": [
        "hong kong",
        "гонконг",
        "гонконґ",
        "гонконг",
        "honkonga",
        "hongkong",
        "hong-kong",
        "ホンコン",
        "香港",
        "홍콩",
        "hong kong sar",
    ],
    "Taiwan": [
        "taiwan",
        "тайвань",
        "taivāna",
        "taiwán",
        "taïwan",
        "taivan",
        "台灣",
        "台湾",
        "타이완",
        "대만",
        "タイワン",
    ],
    "Malaysia": [
        "malaysia",
        "малайзія",
        "малайзия",
        "malaizija",
        "maleisië",
        "malaisie",
        "malaysia",
        "malasia",
        "malásia",
        "マレーシア",
        "malezja",
        "malezya",
        "马来西亚",
        "말레이시아",
        "malesia",
        "malezija",
        "malajzia",
    ],
    "Brazil": [
        "brazil",
        "бразилія",
        "бразилия",
        "brazīlija",
        "brazilië",
        "brésil",
        "brasilien",
        "brasile",
        "brasil",
        "ブラジル",
        "brazylia",
        "brezilya",
        "巴西",
        "브라질",
        "brasilia",
        "brazilija",
        "brazílie",
        "brazília",
    ],
    "Mexico": [
        "mexico",
        "мексика",
        "meksika",
        "mexique",
        "messico",
        "méxico",
        "メキシコ",
        "meksyk",
        "墨西哥",
        "멕시코",
        "meksiko",
        "mehika",
        "mexiko",
        "meksiko",
    ],
    "Argentina": [
        "argentina",
        "аргентина",
        "argentīna",
        "argentinië",
        "argentine",
        "argentinien",
        "アルゼンチン",
        "argentyna",
        "arjantin",
        "阿根廷",
        "아르헨티나",
        "argentiina",
        "argentina",
    ],
    "Chile": [
        "chile",
        "чилі",
        "чили",
        "čīle",
        "tšiili",
        "チリ",
        "şili",
        "智利",
        "칠레",
        "čile",
        "čilė",
    ],
    # ---------------- Tier 3 ----------------
    "India": [
        "india",
        "індія",
        "индия",
        "indija",
        "indien",
        "inde",
        "índia",
        "インド",
        "indie",
        "hindistan",
        "印度",
        "인도",
        "intia",
        "indija",
        "indie",
    ],
    "Indonesia": [
        "indonesia",
        "індонезія",
        "индонезия",
        "indonēzija",
        "indonesië",
        "indonésie",
        "indonésia",
        "インドネシア",
        "endonezya",
        "印度尼西亚",
        "인도네시아",
        "indonesia",
        "indonezija",
        "indonésie",
    ],
    "Philippines": [
        "philippines",
        "філіппіни",
        "филиппины",
        "filipīnas",
        "filipijnen",
        "filippinen",
        "filippine",
        "filipinas",
        "フィリピン",
        "filipiny",
        "filipinler",
        "菲律宾",
        "필리핀",
        "filippiinit",
        "filipini",
        "filipíny",
    ],
    "Thailand": [
        "thailand",
        "таїланд",
        "таиланд",
        "taizeme",
        "thaïlande",
        "tailandia",
        "tailândia",
        "tailandia",
        "タイ",
        "tajlandia",
        "tayland",
        "泰国",
        "태국",
        "thaimaa",
        "tajska",
        "thajsko",
    ],
    "Vietnam": [
        "vietnam",
        "в'єтнам",
        "в’єтнам",
        "вьетнам",
        "vjetnama",
        "viëtnam",
        "viet nam",
        "vietnam",
        "ベトナム",
        "wietnam",
        "越南",
        "베트남",
        "vietnam",
        "vijetnam",
    ],
    "China": [
        "china",
        "китай",
        "ķīna",
        "chine",
        "cina",
        "中国",
        "中國",
        "chiny",
        "çin",
        "kiina",
        "kitajska",
        "čína",
        "tiongkok",
        "중국",
    ],
    "Pakistan": [
        "pakistan",
        "пакистан",
        "pakistāna",
        "pakistan",
        "pakistán",
        "paquistão",
        "パキスタン",
        "巴基斯坦",
        "파키스탄",
        "pákistán",
        "pakistan",
    ],
    "Bangladesh": [
        "bangladesh",
        "бангладеш",
        "bangladeša",
        "bangladesh",
        "bangladés",
        "バングラデシュ",
        "孟加拉国",
        "방글라데시",
        "bangladéš",
    ],
    "Iran": [
        "iran",
        "іран",
        "иран",
        "irāna",
        "iran",
        "irão",
        "イラン",
        "伊朗",
        "이란",
    ],
    "Iraq": [
        "iraq",
        "ірак",
        "ирак",
        "irāka",
        "irak",
        "iraque",
        "イラク",
        "伊拉克",
        "이라크",
    ],
    "Lebanon": [
        "lebanon",
        "ліван",
        "ливан",
        "libāna",
        "libanon",
        "liban",
        "libano",
        "líbano",
        "レバノン",
        "黎巴嫩",
        "레바논",
    ],
    "Nigeria": [
        "nigeria",
        "нігерія",
        "нигерия",
        "nigērija",
        "nigéria",
        "ナイジェリア",
        "nijerya",
        "尼日利亚",
        "나이지리아",
    ],
    "Egypt": [
        "egypt",
        "єгипет",
        "египет",
        "ēģipte",
        "egypte",
        "égypte",
        "ägypten",
        "egitto",
        "egipto",
        "egito",
        "エジプト",
        "egipt",
        "mısır",
        "埃及",
        "이집트",
        "egypti",
        "egipt",
    ],
    "Morocco": [
        "morocco",
        "марокко",
        "maroka",
        "marokko",
        "maroc",
        "marocco",
        "marruecos",
        "marrocos",
        "モロッコ",
        "fas",
        "摩洛哥",
        "모로코",
        "maroko",
        "maroko",
    ],
    "Kenya": [
        "kenya",
        "кенія",
        "кения",
        "kenija",
        "kenia",
        "quênia",
        "ケニア",
        "肯尼亚",
        "케냐",
    ],
    "South Africa": [
        "south africa",
        "південна африка",
        "южная африка",
        "südafrika",
        "afrique du sud",
        "sudafrica",
        "sudáfrica",
        "áfrica do sul",
        "zuid-afrika",
        "dienvidāfrika",
        "南アフリカ",
        "rpa",
        "güney afrika",
        "南非",
        "남아프리카",
        "etelä-afrikka",
        "južna afrika",
        "jihoafrická republika",
    ],
    "Algeria": [
        "algeria",
        "алжир",
        "alžīrija",
        "algerije",
        "algérie",
        "algerien",
        "argelia",
        "argélia",
        "アルジェリア",
        "cezayir",
        "阿尔及利亚",
        "알제리",
        "alžirija",
        "alžírsko",
    ],
    "Tunisia": [
        "tunisia",
        "туніс",
        "тунис",
        "tunisija",
        "tunesië",
        "tunisie",
        "tunesien",
        "túnez",
        "tunísia",
        "チュニジア",
        "tunus",
        "突尼斯",
        "튀니지",
        "tunizija",
        "tunisko",
    ],
    "Ghana": [
        "ghana",
        "гана",
        "gana",
        "ganā",
        "ガーナ",
        "加纳",
        "가나",
    ],
    "Cameroon": [
        "cameroon",
        "камерун",
        "kamerūna",
        "kameroen",
        "cameroun",
        "kamerun",
        "camerun",
        "camerún",
        "camarões",
        "カメルーン",
        "喀麦隆",
        "카메룬",
    ],
    "Senegal": [
        "senegal",
        "сенегал",
        "senegāla",
        "sénégal",
        "senegal",
        "セネガル",
        "塞内加尔",
        "세네갈",
    ],
    "Colombia": [
        "colombia",
        "колумбія",
        "колумбия",
        "kolumbija",
        "colombie",
        "kolumbien",
        "colômbia",
        "コロンビア",
        "kolombiya",
        "哥伦比亚",
        "콜롬비아",
        "kolumbia",
    ],
    "Peru": [
        "peru",
        "перу",
        "peru",
        "pérou",
        "perú",
        "ペルー",
        "秘鲁",
        "페루",
        "perú",
    ],
    "Venezuela": [
        "venezuela",
        "венесуела",
        "венесуэла",
        "venecuēla",
        "vénézuéla",
        "ベネズエラ",
        "venezuela",
        "venezüella",
        "委内瑞拉",
        "베네수엘라",
    ],
    "Ecuador": [
        "ecuador",
        "еквадор",
        "эквадор",
        "ekvadora",
        "équateur",
        "ekuador",
        "エクアドル",
        "ekvador",
        "厄瓜多尔",
        "에콰도르",
    ],
    "Dominican Republic": [
        "dominican republic",
        "домініканська республіка",
        "доминиканская республика",
        "dominikānas republika",
        "dominicaanse republiek",
        "république dominicaine",
        "dominikanische republik",
        "repubblica dominicana",
        "república dominicana",
        "ドミニカ共和国",
        "republika dominikany",
        "dominik cumhuriyeti",
        "多米尼加共和国",
        "도미니카 공화국",
        "dominikaaninen tasavalta",
        "dominikanska republika",
        "dominikánska republika",
        "dominikánská republika",
    ],
}


TIERS: dict[str, list[str]] = {
    "Tier 1 — Premium": [
        "USA",
        "UK",
        "Canada",
        "Australia",
        "New Zealand",
        "Germany",
        "France",
        "Netherlands",
        "Switzerland",
        "Austria",
        "Belgium",
        "Sweden",
        "Norway",
        "Denmark",
        "Finland",
        "Ireland",
        "Iceland",
        "Luxembourg",
        "Japan",
        "South Korea",
        "Singapore",
        "Israel",
    ],
    "Tier 2 — Developed": [
        "Italy",
        "Spain",
        "Portugal",
        "Greece",
        "Poland",
        "Czech Republic",
        "Hungary",
        "Slovakia",
        "Croatia",
        "Romania",
        "Bulgaria",
        "Serbia",
        "Russia",
        "Ukraine",
        "Turkey",
        "UAE",
        "Saudi Arabia",
        "Hong Kong",
        "Taiwan",
        "Malaysia",
        "Brazil",
        "Mexico",
        "Argentina",
        "Chile",
    ],
    "Tier 3 — Emerging": [
        "India",
        "Indonesia",
        "Philippines",
        "Thailand",
        "Vietnam",
        "China",
        "Pakistan",
        "Bangladesh",
        "Iran",
        "Iraq",
        "Lebanon",
        "Nigeria",
        "Egypt",
        "Morocco",
        "Kenya",
        "South Africa",
        "Algeria",
        "Tunisia",
        "Ghana",
        "Cameroon",
        "Senegal",
        "Colombia",
        "Peru",
        "Venezuela",
        "Ecuador",
        "Dominican Republic",
    ],
}

EMPTY_COUNTRY_VALUES = {
    "",
    "не поширюється",
    "не применяется",
    "n/a",
    "—",
    "not shared",
    "nicht geteilt",
    "non condiviso",
    "no compartido",
    "niet gedeeld",
    "non partagé",
    "nepasidalinta",
    "nesdalīts",
}


def build_allowed_set(checked_keys: list[str], custom_text: str) -> set[str]:
    """Build a lowercased set of acceptable country_account values.

    `checked_keys` — list of canonical English keys from COUNTRIES.
    `custom_text` — free-form latin input, comma- or newline-separated.
    """
    allowed: set[str] = set()
    for key in checked_keys:
        for variant in COUNTRIES.get(key, []):
            allowed.add(variant.lower().strip())

    if custom_text:
        for token in custom_text.replace("\n", ",").split(","):
            token = token.strip().lower()
            if token:
                allowed.add(token)

    return allowed
